name: "Go vulnerabilities Action"
description: "Run the Go vulnerability checker"
author: "opzkit"
inputs:
  packages:
    description: 'Run govulncheck on these packages.'
    required: false
    default: './...'
  go-version:
    description: 'The go version to use when running govulncheck'
    required: false
    default: '1.19'
  govuln-version:
    description: 'The govulncheck version to use whe'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - name: Get govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@${{ inputs.govuln-version }}
      shell: bash
    - name: Run govulncheck
      run: govulncheck ${{ inputs.packages }}
      shell: bash

branding:
  icon: 'alert-triangle'
  color: 'red'
